import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Activity, Zap } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import Card from "../components/Card";
import ToggleSwitch from "../components/ToggleSwitch";
import { aiModules, modelPerformance } from "../data/adminData";
import { colors } from "../theme/colors";
export default function AdminAIControls() { const [modules, setModules] = useState(aiModules); const active = modules.filter((item) => item.enabled).length; return <AdminPage title="AI Controls" subtitle="Configure intelligent travel services"><View style={styles.summary}><Card style={styles.summaryCard}><Activity size={19} color={colors.palmGreen} /><View><Text style={styles.value}>{active} / {modules.length}</Text><Text style={styles.sub}>AI modules active</Text></View></Card><Card style={styles.summaryCard}><Zap size={19} color={colors.sunsetCoral} /><View><Text style={styles.value}>93%</Text><Text style={styles.sub}>Average model accuracy</Text></View></Card></View><View style={styles.grid}>{modules.map((module) => { const Icon = module.icon; return <Card key={module.id} style={styles.module}><View style={styles.moduleHeader}><View style={styles.icon}><Icon size={20} color={colors.oceanBlue} /></View><ToggleSwitch checked={module.enabled} onChange={(enabled) => setModules((current) => current.map((item) => item.id === module.id ? { ...item, enabled } : item))} /></View><Text style={styles.name}>{module.title}</Text><Text style={styles.sub}>{module.description}</Text><View style={styles.footer}><Text style={styles.tag}>{module.tag}</Text><Text style={styles.accuracy}>{module.accuracy || "—"}</Text></View></Card>; })}</View><Card style={styles.performance}><Text style={styles.name}>Model performance — last 7 days</Text><View style={styles.bars}>{modelPerformance.map((item, index) => <View key={`${item.day}-${index}`} style={styles.barColumn}><View style={[styles.bar, { height: `${item.accuracy}%` }]} /><Text style={styles.sub}>{item.day}</Text></View>)}</View></Card></AdminPage>; }
const styles = StyleSheet.create({ summary: { flexDirection: "row", gap: 20, marginBottom: 24 }, summaryCard: { flex: 1, flexDirection: "row", alignItems: "center", gap: 12 }, value: { fontFamily: "Poppins", fontSize: 22, fontWeight: "700", color: colors.textPrimary }, sub: { marginTop: 4, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 20 }, module: { width: "31%", minWidth: 260 }, moduleHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 14 }, icon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: colors.oceanBlueLight }, name: { fontFamily: "Poppins", fontSize: 15, fontWeight: "700", color: colors.textPrimary }, footer: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 16 }, tag: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, backgroundColor: colors.oceanBlueLight, fontFamily: "DMSans", fontSize: 10, color: colors.oceanBlue }, accuracy: { fontFamily: "DMSans", fontSize: 12, fontWeight: "700", color: colors.palmGreen }, performance: { marginTop: 24 }, bars: { height: 130, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around", marginTop: 16 }, barColumn: { height: "100%", alignItems: "center", justifyContent: "flex-end", gap: 6 }, bar: { width: 22, minHeight: 10, borderRadius: 5, backgroundColor: colors.sunsetCoral } });
