import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Plus, Search } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import Card from "../components/Card";
import StatusBadge from "../components/StatusBadge";
import { api } from "../lib/api";
import { colors } from "../theme/colors";
const filters = ["All", "BUS", "JEEPNEY", "TRICYCLE"];
export default function AdminRoutes() { const [routes, setRoutes] = useState([]); const [filter, setFilter] = useState("All"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { api.getTransitRoutes().then(setRoutes).catch(() => {}).finally(() => setLoading(false)); }, []); const visible = routes.filter((route) => (filter === "All" || route.type === filter) && route.name.toLowerCase().includes(query.toLowerCase())); return <AdminPage title="Route Management" subtitle={`${routes.length} transit routes in Pangasinan`} actions={<Pressable style={styles.add}><Plus size={16} color={colors.white} /><Text style={styles.addText}>Add Route</Text></Pressable>}><View style={styles.toolbar}><View style={styles.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</View><View style={styles.search}><Search size={15} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search routes..." style={styles.input} /></View></View><Card style={styles.list}>{loading ? <ActivityIndicator color={colors.oceanBlue} /> : visible.map((route, index) => <View key={route.id} style={[styles.row, index < visible.length - 1 && styles.border]}><View style={styles.routeInfo}><Text style={styles.name}>{route.name}</Text><Text style={styles.sub}>{route.type} · {route.stops} stops · every {route.frequency}</Text></View><Text style={styles.passengers}>{route.passengers?.toLocaleString() || 0} riders</Text><StatusBadge status={route.status?.toLowerCase()} /></View>)}</Card></AdminPage>; }
const styles = StyleSheet.create({ add: { flexDirection: "row", gap: 8, alignItems: "center", paddingHorizontal: 18, paddingVertical: 11, borderRadius: 10, backgroundColor: colors.oceanBlue }, addText: { fontFamily: "DMSans", fontWeight: "700", color: colors.white }, toolbar: { flexDirection: "row", justifyContent: "space-between", gap: 12, marginBottom: 20 }, filters: { flexDirection: "row", gap: 8 }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 9 }, filterActive: { backgroundColor: colors.oceanBlue }, filterText: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted }, filterTextActive: { fontWeight: "700", color: colors.white }, search: { flexDirection: "row", alignItems: "center", width: 220, gap: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.white }, input: { flex: 1, paddingVertical: 8, fontFamily: "DMSans", fontSize: 13, color: colors.textPrimary }, list: { padding: 0 }, row: { flexDirection: "row", alignItems: "center", gap: 18, padding: 18 }, border: { borderBottomWidth: 1, borderBottomColor: colors.border }, routeInfo: { flex: 1 }, name: { fontFamily: "DMSans", fontSize: 14, fontWeight: "700", color: colors.textPrimary }, sub: { marginTop: 3, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted }, passengers: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted } });
