import { StyleSheet, Text, View } from "react-native";
import { Route, TrendingUp, Users, Wallet } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import AdminStatCard from "../components/AdminStatCard";
import Card from "../components/Card";
import { growthData, topDestinations, weeklyUserActivity } from "../data/adminData";
import { colors } from "../theme/colors";
function Bars({ data, keyName, color }) { const max = Math.max(...data.map((item) => item[keyName])); return <View style={styles.bars}>{data.map((item) => <View key={item.month || item.day} style={styles.barColumn}><View style={[styles.bar, { height: `${(item[keyName] / max) * 100}%`, backgroundColor: color }]} /><Text style={styles.label}>{item.month || item.day}</Text></View>)}</View>; }
export default function AdminAnalytics() { return <AdminPage title="Analytics" subtitle="Pangasinan Province · Aug 2026 · All channels"><View style={styles.stats}><AdminStatCard label="Total Users" value="4,821" delta="+12.4%" icon={<Users size={18} color={colors.oceanBlue} />} iconBg={colors.oceanBlueLight} dividerColor={colors.oceanBlue} /><AdminStatCard label="Trips Created" value="2,240" delta="+8.2%" icon={<Route size={18} color={colors.palmGreen} />} iconBg={colors.palmGreenLight} dividerColor={colors.palmGreen} /><AdminStatCard label="Revenue" value="₱118K" delta="+15.6%" icon={<Wallet size={18} color={colors.gold} />} iconBg={colors.goldLight} dividerColor={colors.gold} /><AdminStatCard label="Retention" value="68%" delta="+2.1%" icon={<TrendingUp size={18} color={colors.sunsetCoral} />} iconBg={colors.coralLight} dividerColor={colors.sunsetCoral} /></View><View style={styles.columns}><Card style={styles.flex}><Text style={styles.heading}>User growth</Text><Bars data={growthData} keyName="users" color={colors.oceanBlue} /></Card><Card style={styles.flex}><Text style={styles.heading}>Weekly activity</Text><Bars data={weeklyUserActivity} keyName="users" color={colors.sunsetCoral} /></Card></View><Card><Text style={styles.heading}>Top destinations</Text>{topDestinations.map((destination, index) => { const Icon = destination.icon; return <View key={destination.name} style={[styles.destination, index < topDestinations.length - 1 && styles.border]}><Icon size={17} color={colors.oceanBlue} /><Text style={styles.destinationName}>{destination.name}</Text><Text style={styles.destinationValue}>{destination.value.toLocaleString()} trips</Text></View>; })}</Card></AdminPage>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", gap: 20, marginBottom: 24 }, columns: { flexDirection: "row", gap: 20, marginBottom: 24 }, flex: { flex: 1 }, heading: { fontFamily: "Poppins", fontSize: 17, fontWeight: "700", color: colors.oceanBlue }, bars: { height: 170, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around", marginTop: 16 }, barColumn: { height: "100%", alignItems: "center", justifyContent: "flex-end", gap: 7 }, bar: { width: 24, minHeight: 8, borderRadius: 5 }, label: { fontFamily: "DMSans", fontSize: 11, color: colors.textMuted }, destination: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 13 }, border: { borderBottomWidth: 1, borderBottomColor: colors.border }, destinationName: { flex: 1, fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textPrimary }, destinationValue: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted } });
