import { Pressable, StyleSheet, Text, View } from "react-native";
import { Activity, Radio, Route, Users, Wallet } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import AdminStatCard from "../components/AdminStatCard";
import Card from "../components/Card";
import StatusBadge from "../components/StatusBadge";
import { colors } from "../theme/colors";

const routes = [["Dagupan–Alaminos", "Bus", "active"], ["Dagupan–Lingayen", "Jeepney", "active"], ["Alaminos–Bolinao", "Jeepney", "active"], ["Dagupan–Manaoag", "Bus", "inactive"]];
export default function AdminDashboard() { return <AdminPage title="Admin Dashboard" subtitle="Pangasinan travel network overview"><View style={styles.stats}><AdminStatCard label="Total Users" value="4,821" delta="+12.4% this month" icon={<Users size={18} color={colors.oceanBlue} />} iconBg={colors.oceanBlueLight} dividerColor={colors.oceanBlue} /><AdminStatCard label="Active Routes" value="24" delta="3 updated today" icon={<Route size={18} color={colors.palmGreen} />} iconBg={colors.palmGreenLight} dividerColor={colors.palmGreen} /><AdminStatCard label="Geofence Alerts" value="1,248" delta="This week" icon={<Radio size={18} color={colors.sunsetCoral} />} iconBg={colors.coralLight} dividerColor={colors.sunsetCoral} /><AdminStatCard label="Trip Revenue" value="₱118K" delta="+8.2% this month" icon={<Wallet size={18} color={colors.gold} />} iconBg={colors.goldLight} dividerColor={colors.gold} /></View><View style={styles.columns}><Card style={styles.flex}><Text style={styles.heading}>Transit routes</Text>{routes.map(([name, type, status]) => <View key={name} style={styles.item}><View><Text style={styles.name}>{name}</Text><Text style={styles.muted}>{type} · updated today</Text></View><StatusBadge status={status} /></View>)}</Card><Card style={styles.flex}><Text style={styles.heading}>System activity</Text>{[["Live transit updates", "482 events"], ["AI itineraries generated", "126 today"], ["Active geofences", "18 zones"], ["Offline map downloads", "342 today"]].map(([label, value]) => <View key={label} style={styles.item}><View style={styles.activityIcon}><Activity size={16} color={colors.oceanBlue} /></View><View style={styles.flex}><Text style={styles.name}>{label}</Text><Text style={styles.muted}>{value}</Text></View></View>)}</Card></View></AdminPage>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", gap: 20, marginBottom: 24 }, columns: { flexDirection: "row", gap: 20 }, flex: { flex: 1 }, heading: { marginBottom: 12, fontFamily: "Poppins", fontSize: 17, fontWeight: "700", color: colors.oceanBlue }, item: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.border }, name: { fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textPrimary }, muted: { marginTop: 2, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted }, activityIcon: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: colors.oceanBlueLight } });
