import { useAppTheme } from "../theme/useAppTheme";
import { useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { Bell, Radio } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import AdminStatCard from "../components/AdminStatCard";
import Card from "../components/Card";
import ToggleSwitch from "../components/ToggleSwitch";
import { api } from "../lib/api";
import { colors } from "../theme/colors";
export default function AdminGeofences() {
  const { themeStyle, themeColor } = useAppTheme();
 const [zones, setZones] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { api.getGeofences().then(setZones).catch(() => {}).finally(() => setLoading(false)); }, []); const toggle = async (zone) => { const active = !zone.active; setZones((current) => current.map((item) => item.id === zone.id ? { ...item, active } : item)); try { await api.updateGeofence(zone.id, { active }); } catch { setZones((current) => current.map((item) => item.id === zone.id ? zone : item)); } }; const active = zones.filter((zone) => zone.active).length; const alerts = zones.reduce((sum, zone) => sum + (zone.alerts || 0), 0); return <AdminPage title="Geofence Management" subtitle="Manage location-based transit alerts"><View style={themeStyle(styles.stats)}><AdminStatCard label="Active Zones" value={String(active)} delta="Monitoring now" icon={<Radio size={18} color={themeColor(colors.palmGreen, "color")} />} iconBg={colors.palmGreenLight} dividerColor={colors.palmGreen} /><AdminStatCard label="Total Alerts" value={String(alerts)} delta="All zones" icon={<Bell size={18} color={themeColor(colors.sunsetCoral, "color")} />} iconBg={colors.coralLight} dividerColor={colors.sunsetCoral} /></View><Card style={themeStyle(styles.list)}>{loading ? <ActivityIndicator color={themeColor(colors.oceanBlue, "color")} /> : zones.map((zone, index) => <View key={zone.id} style={themeStyle([styles.row, index < zones.length - 1 && styles.border])}><View style={themeStyle(styles.dot)} /><View style={themeStyle(styles.info)}><Text style={themeStyle(styles.name)}>{zone.location}</Text><Text style={themeStyle(styles.sub)}>{zone.zone} · {zone.radius} · {zone.alerts || 0} alerts</Text></View><ToggleSwitch checked={zone.active} onChange={() => toggle(zone)} /></View>)}</Card></AdminPage>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", gap: 20, marginBottom: 24 }, list: { padding: 0 }, row: { flexDirection: "row", alignItems: "center", gap: 14, padding: 18 }, border: { borderBottomWidth: 1, borderBottomColor: colors.border }, dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.sunsetCoral }, info: { flex: 1 }, name: { fontFamily: "DMSans", fontSize: 14, fontWeight: "700", color: colors.textPrimary }, sub: { marginTop: 3, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted } });
