import { useAppTheme } from "../theme/useAppTheme";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { KeyRound, Shield, ShieldAlert } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import Card from "../components/Card";
import ToggleSwitch from "../components/ToggleSwitch";
import { colors } from "../theme/colors";
const services = [["API Server", "Operational"], ["AI Inference", "Operational"], ["GPS Service", "Operational"], ["Push Notifications", "Degraded"], ["Offline Sync", "Operational"], ["Data Backup", "Operational"]];
const initialIntegrations = [["Google Maps API", "AIza••••••••••••Xk9Q", true], ["Anthropic Claude", "sk-ant-••••••••••••", true], ["Firebase FCM", "AAAA••••••••••••", true], ["SMS Gateway", "SG.••••••••••••", false]];
function Section({ title, children }) {
  const { themeStyle } = useAppTheme();
 return <Card style={themeStyle(styles.section)}><Text style={themeStyle(styles.sectionTitle)}>{title}</Text>{children}</Card>; }
export default function AdminSettings() {
  const { themeStyle, themeColor } = useAppTheme();
 const [integrations, setIntegrations] = useState(initialIntegrations); const [maintenance, setMaintenance] = useState(false); return <AdminPage title="Admin Settings" subtitle="System configuration and service health"><View style={themeStyle(styles.columns)}><Section title="System Status">{services.map(([name, status]) => <View key={name} style={themeStyle(styles.row)}><View style={themeStyle(styles.service)}><View style={themeStyle([styles.dot, { backgroundColor: status === "Operational" ? colors.palmGreen : colors.gold }])} /><Text style={themeStyle(styles.name)}>{name}</Text></View><Text style={themeStyle([styles.status, { color: status === "Operational" ? colors.palmGreen : colors.gold }])}>{status}</Text></View>)}</Section><Section title="System Controls"><View style={themeStyle(styles.row)}><View><Text style={themeStyle(styles.name)}>Maintenance mode</Text><Text style={themeStyle(styles.sub)}>Disable user access while updating</Text></View><ToggleSwitch checked={maintenance} onChange={setMaintenance} /></View><View style={themeStyle(styles.row)}><View style={themeStyle(styles.service)}><Shield size={17} color={themeColor(colors.oceanBlue, "color")} /><Text style={themeStyle(styles.name)}>Security audit</Text></View><Pressable style={themeStyle(styles.outline)}><Text style={themeStyle(styles.outlineText)}>Run audit</Text></Pressable></View><View style={themeStyle(styles.row)}><View style={themeStyle(styles.service)}><ShieldAlert size={17} color={themeColor(colors.sunsetCoral, "color")} /><Text style={themeStyle(styles.name)}>Clear cached data</Text></View><Pressable style={themeStyle(styles.danger)}><Text style={themeStyle(styles.dangerText)}>Clear</Text></Pressable></View></Section></View><Section title="Integrations">{integrations.map(([name, key, enabled], index) => <View key={name} style={themeStyle([styles.integration, index < integrations.length - 1 && styles.border])}><View style={themeStyle(styles.integrationInfo)}><View style={themeStyle(styles.service)}><KeyRound size={16} color={themeColor(colors.oceanBlue, "color")} /><Text style={themeStyle(styles.name)}>{name}</Text></View><Text style={themeStyle(styles.sub)}>{key}</Text></View><ToggleSwitch checked={enabled} onChange={(value) => setIntegrations((current) => current.map((item) => item[0] === name ? [item[0], item[1], value] : item))} /></View>)}</Section></AdminPage>; }
const styles = StyleSheet.create({ columns: { flexDirection: "row", gap: 20 }, section: { flex: 1, padding: 0, marginBottom: 20 }, sectionTitle: { padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border, fontFamily: "Poppins", fontSize: 16, fontWeight: "700", color: colors.oceanBlue }, row: { minHeight: 64, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16, padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border }, service: { flexDirection: "row", alignItems: "center", gap: 9 }, dot: { width: 9, height: 9, borderRadius: 5 }, name: { fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textPrimary }, sub: { marginTop: 3, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted }, status: { fontFamily: "DMSans", fontSize: 12, fontWeight: "700" }, outline: { paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 9 }, outlineText: { fontFamily: "DMSans", fontSize: 12, fontWeight: "600", color: colors.textPrimary }, danger: { paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1, borderColor: colors.coralLight, borderRadius: 9 }, dangerText: { fontFamily: "DMSans", fontSize: 12, fontWeight: "600", color: colors.sunsetCoral }, integration: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16 }, border: { borderBottomWidth: 1, borderBottomColor: colors.border }, integrationInfo: { flex: 1 } });
