import { useAppTheme } from "../theme/useAppTheme";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Search, UserPlus } from "lucide-react-native";
import AdminPage from "../components/AdminPage";
import Card from "../components/Card";
import { api } from "../lib/api";
import { colors } from "../theme/colors";
const filters = ["All", "PRO", "EXPLORER"];
const roleColors = { PRO: [colors.goldLight, colors.gold], EXPLORER: [colors.oceanBlueLight, colors.oceanBlue], ADMIN: [colors.palmGreenLight, colors.palmGreen] };
export default function AdminUsers() {
  const { themeStyle, themeColor } = useAppTheme();
 const [users, setUsers] = useState([]); const [filter, setFilter] = useState("All"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { api.getAllUsers().then(setUsers).catch(() => {}).finally(() => setLoading(false)); }, []); const visible = users.filter((user) => (filter === "All" || user.role === filter) && `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())); return <AdminPage title="User Management" subtitle={`${users.length} registered travelers`} actions={<Pressable style={themeStyle(styles.add)}><UserPlus size={16} color={themeColor(colors.white, "color")} /><Text style={themeStyle(styles.addText)}>Invite User</Text></Pressable>}><View style={themeStyle(styles.toolbar)}><View style={themeStyle(styles.filters)}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={themeStyle([styles.filter, filter === item && styles.filterActive])}><Text style={themeStyle([styles.filterText, filter === item && styles.filterTextActive])}>{item}</Text></Pressable>)}</View><View style={themeStyle(styles.search)}><Search size={15} color={themeColor(colors.textMuted, "color")} /><TextInput value={query} onChangeText={setQuery} placeholder="Search users..." style={themeStyle(styles.input)} /></View></View><Card style={themeStyle(styles.list)}>{loading ? <ActivityIndicator color={themeColor(colors.oceanBlue, "color")} /> : visible.map((user, index) => { const [backgroundColor, color] = roleColors[user.role] || roleColors.EXPLORER; const initials = user.name?.split(" ").map((part) => part[0]).slice(0, 2).join("") || "U"; return <View key={user.id} style={themeStyle([styles.row, index < visible.length - 1 && styles.border])}><View style={themeStyle(styles.avatar)}><Text style={themeStyle(styles.avatarText)}>{initials}</Text></View><View style={themeStyle(styles.info)}><Text style={themeStyle(styles.name)}>{user.name}</Text><Text style={themeStyle(styles.sub)}>{user.email} · joined {new Date(user.createdAt).toLocaleDateString()}</Text></View><Text style={themeStyle([styles.role, { backgroundColor, color }])}>{user.role}</Text></View>; })}</Card></AdminPage>; }
const styles = StyleSheet.create({ add: { flexDirection: "row", gap: 8, alignItems: "center", paddingHorizontal: 18, paddingVertical: 11, borderRadius: 10, backgroundColor: colors.oceanBlue }, addText: { fontFamily: "DMSans", fontWeight: "700", color: colors.white }, toolbar: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 }, filters: { flexDirection: "row", gap: 8 }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 9 }, filterActive: { backgroundColor: colors.oceanBlue }, filterText: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted }, filterTextActive: { fontWeight: "700", color: colors.white }, search: { width: 220, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.white }, input: { flex: 1, paddingVertical: 8, fontFamily: "DMSans", fontSize: 13, color: colors.textPrimary }, list: { padding: 0 }, row: { flexDirection: "row", alignItems: "center", gap: 14, padding: 18 }, border: { borderBottomWidth: 1, borderBottomColor: colors.border }, avatar: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.sunsetCoral }, avatarText: { fontFamily: "Poppins", fontWeight: "700", color: colors.white }, info: { flex: 1 }, name: { fontFamily: "DMSans", fontSize: 14, fontWeight: "700", color: colors.textPrimary }, sub: { marginTop: 3, fontFamily: "DMSans", fontSize: 12, color: colors.textMuted }, role: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 999, fontFamily: "DMSans", fontSize: 11, fontWeight: "600" } });
