import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Plus } from "lucide-react-native";
import Card from "../components/Card";
import { api } from "../lib/api";
import { colors } from "../theme/colors";
import { placeIconMap } from "../utils/placeIcons";

const tabs = [["all", "All"], ["UPCOMING", "Upcoming"], ["COMPLETED", "Completed"]];

function TripCard({ trip }) {
  const Icon = placeIconMap[trip.icon] ?? placeIconMap.landmark;
  const completed = trip.status === "COMPLETED";
  const progress = trip.budget ? Math.min(100, (trip.spent / trip.budget) * 100) : 0;
  return <Card style={styles.tripCard}><View style={styles.tripTop}><View style={styles.icon}><Icon size={20} color={colors.oceanBlue} /></View><Text style={[styles.status, { color: completed ? colors.palmGreen : colors.sunsetCoral, backgroundColor: completed ? colors.palmGreenLight : colors.coralLight }]}>{trip.status.toLowerCase()}</Text></View><Text style={styles.tripTitle}>{trip.title}</Text><Text style={styles.muted}>{trip.location} · {trip.date}</Text><View style={styles.budgetRow}><Text style={styles.muted}>Budget progress</Text><Text style={styles.amount}>₱{trip.spent.toLocaleString()} / ₱{trip.budget.toLocaleString()}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${progress}%`, backgroundColor: completed ? colors.palmGreen : colors.sunsetCoral }]} /></View><View style={styles.tripFooter}><Text style={styles.muted}>{trip.stops} stops planned</Text><View style={styles.actions}><Pressable style={styles.outline}><Text style={styles.outlineText}>View</Text></Pressable><Pressable style={styles.primary}><Text style={styles.primaryText}>Edit</Text></Pressable></View></View></Card>;
}

export default function MyTrips() {
  const [filter, setFilter] = useState("all"); const [trips, setTrips] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { api.getTrips().then(setTrips).catch(() => {}).finally(() => setLoading(false)); }, []);
  const filtered = filter === "all" ? trips : trips.filter((trip) => trip.status === filter);
  const upcoming = trips.filter((trip) => trip.status === "UPCOMING").length; const complete = trips.filter((trip) => trip.status === "COMPLETED").length;
  return <ScrollView contentContainerStyle={styles.screen}><View style={styles.header}><View><Text style={styles.title}>My Trips</Text><Text style={styles.muted}>{upcoming} upcoming · {complete} completed</Text></View><Pressable style={styles.newTrip}><Plus size={16} color={colors.white} /><Text style={styles.primaryText}>New Trip</Text></Pressable></View><View style={styles.tabs}>{tabs.map(([key, label]) => <Pressable key={key} onPress={() => setFilter(key)} style={[styles.tab, filter === key && styles.tabActive]}><Text style={[styles.tabText, filter === key && styles.tabTextActive]}>{label}</Text></Pressable>)}</View>{loading ? <ActivityIndicator color={colors.oceanBlue} /> : filtered.length ? <View style={styles.grid}>{filtered.map((trip) => <TripCard key={trip.id} trip={trip} />)}</View> : <Text style={styles.empty}>No trips found.</Text>}</ScrollView>;
}

const styles = StyleSheet.create({ screen: { flexGrow: 1, padding: 28, backgroundColor: colors.warmSand }, header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginBottom: 20 }, title: { fontFamily: "Poppins", fontSize: 26, fontWeight: "700", color: colors.oceanBlue }, muted: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted, marginTop: 4 }, newTrip: { flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12, backgroundColor: colors.sunsetCoral }, primaryText: { fontFamily: "DMSans", fontSize: 14, fontWeight: "700", color: colors.white }, tabs: { flexDirection: "row", gap: 8, marginBottom: 24 }, tab: { paddingHorizontal: 20, paddingVertical: 9, borderRadius: 10 }, tabActive: { backgroundColor: colors.oceanBlue }, tabText: { fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textMuted }, tabTextActive: { color: colors.white }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 20 }, tripCard: { width: "47%", minWidth: 290 }, tripTop: { flexDirection: "row", justifyContent: "space-between", marginBottom: 14 }, icon: { width: 44, height: 44, borderRadius: 12, backgroundColor: colors.oceanBlueLight, alignItems: "center", justifyContent: "center" }, status: { fontFamily: "DMSans", fontSize: 11, fontWeight: "600", paddingHorizontal: 12, paddingVertical: 4, borderRadius: 999, alignSelf: "flex-start" }, tripTitle: { fontFamily: "Poppins", fontSize: 17, fontWeight: "700", color: colors.oceanBlue }, budgetRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginTop: 20, marginBottom: 6 }, amount: { fontFamily: "DMSans", fontSize: 13, fontWeight: "700", color: colors.textPrimary }, track: { height: 6, borderRadius: 999, backgroundColor: "#EFEAE0", overflow: "hidden" }, fill: { height: "100%", borderRadius: 999 }, tripFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 18, gap: 8 }, actions: { flexDirection: "row", gap: 8 }, outline: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8 }, outlineText: { fontFamily: "DMSans", fontSize: 13, fontWeight: "600", color: colors.textPrimary }, primary: { borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: colors.oceanBlue }, empty: { marginTop: 60, fontFamily: "DMSans", textAlign: "center", color: colors.textMuted } });
