import { FeedbackPressable } from "../components/WorkspaceMotion";
import { useAppTheme } from "../theme/useAppTheme";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Download, RefreshCw, Trash2 } from "lucide-react-native";
import Card from "../components/Card";
import WovenDivider from "../components/WovenDivider";
import { offlineRegions, offlineStorageCapMB } from "../data/places";
import { colors } from "../theme/colors";

export default function OfflineMaps() {
  const { themeStyle, themeColor } = useAppTheme();
 const [regions, setRegions] = useState(offlineRegions); const toggle = (id) => setRegions((current) => current.map((region) => region.id === id ? { ...region, downloaded: !region.downloaded } : region)); const downloaded = regions.filter((region) => region.downloaded); const used = downloaded.reduce((sum, region) => sum + region.sizeMB, 0); const percentage = (used / offlineStorageCapMB) * 100; return <ScrollView contentContainerStyle={themeStyle(styles.screen)}><View style={themeStyle(styles.header)}><View><Text style={themeStyle(styles.title)}>Offline Maps</Text><Text style={themeStyle(styles.sub)}>Download regions for offline navigation</Text></View><Pressable style={themeStyle(styles.sync)}><RefreshCw size={15} color={themeColor(colors.textPrimary, "color")} /><Text style={themeStyle(styles.syncText)}>Sync All</Text></Pressable></View><Card style={themeStyle(styles.summary)}><WovenDivider color={themeColor(colors.oceanBlue, "color")} count={40} /><View style={themeStyle(styles.summaryRow)}><View><Text style={themeStyle(styles.eyebrow)}>STORAGE USED</Text><View style={themeStyle(styles.storage)}><Text style={themeStyle(styles.used)}>{used} MB</Text><Text style={themeStyle(styles.total)}>/ {offlineStorageCapMB} MB</Text></View></View><View><Text style={themeStyle(styles.eyebrow)}>DOWNLOADED</Text><Text style={themeStyle(styles.count)}>{downloaded.length}</Text><Text style={themeStyle(styles.sub)}>regions</Text></View></View><View style={themeStyle(styles.track)}><View style={themeStyle([styles.fill, { width: `${percentage}%` }])} /></View><Text style={themeStyle(styles.sub)}>{offlineStorageCapMB - used} MB free</Text></Card><Text style={themeStyle(styles.sectionTitle)}>Pangasinan Regions</Text><Card style={themeStyle(styles.list)}>{regions.map((region, index) => <View key={region.id} style={themeStyle([styles.region, index < regions.length - 1 && styles.divider])}><View style={themeStyle([styles.downloadIcon, { backgroundColor: region.downloaded ? colors.palmGreenLight : "#F0F0F0" }])}><Download size={17} color={themeColor(region.downloaded ? colors.palmGreen : colors.textMuted, "color")} /></View><View style={themeStyle(styles.regionInfo)}><Text style={themeStyle(styles.regionName)}>{region.name}</Text><Text style={themeStyle(styles.sub)}>{region.description} · {region.sizeMB} MB</Text></View>{region.downloaded ? <View style={themeStyle(styles.downloadedActions)}><Text style={themeStyle(styles.downloaded)}>Downloaded</Text><FeedbackPressable onPress={() => toggle(region.id)} style={themeStyle(styles.remove)}><Trash2 size={13} color={themeColor(colors.sunsetCoral, "color")} /><Text style={themeStyle(styles.removeText)}>Remove</Text></FeedbackPressable></View> : <FeedbackPressable onPress={() => toggle(region.id)} style={themeStyle(styles.download)}><Text style={themeStyle(styles.downloadText)}>Download</Text></FeedbackPressable>}</View>)}</Card></ScrollView>; }
const styles = StyleSheet.create({ screen: { flexGrow: 1, padding: 28, backgroundColor: colors.warmSand }, header: { flexDirection: "row", justifyContent: "space-between", gap: 16, marginBottom: 24 }, title: { fontFamily: "Poppins", fontSize: 26, fontWeight: "700", color: colors.oceanBlue }, sub: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted, marginTop: 4 }, sync: { flexDirection: "row", alignItems: "center", gap: 8, alignSelf: "flex-start", borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 11, backgroundColor: colors.white }, syncText: { fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textPrimary }, summary: { marginBottom: 28 }, summaryRow: { flexDirection: "row", justifyContent: "space-between" }, eyebrow: { fontFamily: "DMSans", fontSize: 11, fontWeight: "600", letterSpacing: .5, color: colors.textMuted }, storage: { flexDirection: "row", alignItems: "baseline", gap: 8 }, used: { fontFamily: "Poppins", fontSize: 32, fontWeight: "700", color: colors.textPrimary }, total: { fontFamily: "DMSans", fontSize: 15, color: colors.textMuted }, count: { fontFamily: "Poppins", fontSize: 20, fontWeight: "700", color: colors.oceanBlue }, track: { height: 8, marginTop: 16, marginBottom: 8, overflow: "hidden", borderRadius: 999, backgroundColor: "#EFEAE0" }, fill: { height: "100%", borderRadius: 999, backgroundColor: colors.oceanBlue }, sectionTitle: { marginBottom: 16, fontFamily: "Poppins", fontSize: 18, fontWeight: "700", color: colors.oceanBlue }, list: { padding: 0 }, region: { flexDirection: "row", alignItems: "center", gap: 16, padding: 18 }, divider: { borderBottomWidth: 1, borderBottomColor: colors.border }, downloadIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, regionInfo: { flex: 1 }, regionName: { fontFamily: "DMSans", fontSize: 14, fontWeight: "600", color: colors.textPrimary }, downloadedActions: { flexDirection: "row", alignItems: "center", gap: 10 }, downloaded: { fontFamily: "DMSans", fontSize: 11, fontWeight: "600", paddingHorizontal: 12, paddingVertical: 4, borderRadius: 999, color: colors.palmGreen, backgroundColor: colors.palmGreenLight }, remove: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 16, paddingVertical: 8, borderWidth: 1, borderColor: colors.coralLight, borderRadius: 10 }, removeText: { fontFamily: "DMSans", fontSize: 13, fontWeight: "600", color: colors.sunsetCoral }, download: { paddingHorizontal: 20, paddingVertical: 9, borderRadius: 10, backgroundColor: colors.oceanBlue }, downloadText: { fontFamily: "DMSans", fontSize: 13, fontWeight: "600", color: colors.white } });
