import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Navigation, Plus, Search, X } from "lucide-react-native";
import { api } from "../lib/api";
import { colors } from "../theme/colors";
import { placeIconMap } from "../utils/placeIcons";

const categories = { "Nature Park": [colors.palmGreenLight, colors.palmGreen], Beach: [colors.coralLight, colors.sunsetCoral], Religious: [colors.goldLight, colors.gold], Restaurant: [colors.palmGreenLight, colors.palmGreen], Landmark: [colors.oceanBlueLight, colors.oceanBlue], Waterway: [colors.coralLight, colors.sunsetCoral] };

function PlaceCard({ place, onDelete }) { const Icon = placeIconMap[place.icon] ?? placeIconMap.landmark; const [backgroundColor, color] = categories[place.category] ?? [colors.oceanBlueLight, colors.oceanBlue]; return <View style={styles.card}><View style={styles.art}><View style={styles.icon}><Icon size={24} color={colors.oceanBlue} /></View></View><View style={styles.cardBody}><View style={styles.cardTitle}><Text style={styles.name} numberOfLines={1}>{place.name}</Text><Text style={[styles.badge, { backgroundColor, color }]}>{place.category}</Text></View><Text style={styles.description}>{place.description || "No description available."}</Text><View style={styles.actions}><Pressable style={styles.add}><Text style={styles.addText}>Add to Trip</Text></Pressable><Pressable accessibilityLabel="Get directions" style={styles.iconButton}><Navigation size={15} color={colors.oceanBlue} /></Pressable><Pressable accessibilityLabel={`Remove ${place.name}`} onPress={() => onDelete(place.id)} style={[styles.iconButton, styles.remove]}><X size={15} color={colors.sunsetCoral} /></Pressable></View></View></View>; }

export default function SavedPlaces() { const [places, setPlaces] = useState([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { api.getSavedPlaces().then(setPlaces).catch(() => {}).finally(() => setLoading(false)); }, []); const remove = async (id) => { try { await api.deleteSavedPlace(id); setPlaces((current) => current.filter((place) => place.id !== id)); } catch {} }; const filtered = places.filter((place) => `${place.name} ${place.category}`.toLowerCase().includes(query.toLowerCase())); return <ScrollView contentContainerStyle={styles.screen}><View style={styles.header}><View><Text style={styles.title}>Saved Places</Text><Text style={styles.sub}>{places.length} locations saved</Text></View><View style={styles.headerActions}><View style={styles.search}><Search size={15} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search saved..." placeholderTextColor={colors.textMuted} style={styles.input} /></View><Pressable style={styles.new}><Plus size={16} color={colors.white} /><Text style={styles.newText}>Add Place</Text></Pressable></View></View>{loading ? <ActivityIndicator color={colors.oceanBlue} /> : filtered.length ? <View style={styles.grid}>{filtered.map((place) => <PlaceCard key={place.id} place={place} onDelete={remove} />)}</View> : <Text style={styles.empty}>No saved places found.</Text>}</ScrollView>; }
const styles = StyleSheet.create({ screen: { flexGrow: 1, padding: 28, backgroundColor: colors.warmSand }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 24 }, title: { fontFamily: "Poppins", fontSize: 26, fontWeight: "700", color: colors.oceanBlue }, sub: { fontFamily: "DMSans", fontSize: 13, color: colors.textMuted, marginTop: 4 }, headerActions: { flexDirection: "row", gap: 10 }, search: { flexDirection: "row", alignItems: "center", gap: 8, width: 200, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 12, backgroundColor: colors.white }, input: { flex: 1, minWidth: 0, paddingVertical: 10, fontFamily: "DMSans", fontSize: 13, color: colors.textPrimary }, new: { flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 10, paddingHorizontal: 20, backgroundColor: colors.oceanBlue }, newText: { fontFamily: "DMSans", fontSize: 14, fontWeight: "700", color: colors.white }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 20 }, card: { width: "31%", minWidth: 250, overflow: "hidden", borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white }, art: { height: 96, alignItems: "center", justifyContent: "center", backgroundColor: "#F4F6F5" }, icon: { width: 52, height: 52, borderRadius: 26, alignItems: "center", justifyContent: "center", backgroundColor: colors.white, elevation: 2 }, cardBody: { padding: 18 }, cardTitle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, name: { flex: 1, fontFamily: "Poppins", fontWeight: "700", fontSize: 15, color: colors.oceanBlue }, badge: { fontFamily: "DMSans", fontSize: 11, fontWeight: "600", paddingHorizontal: 10, paddingVertical: 3, borderRadius: 999 }, description: { minHeight: 36, marginTop: 6, marginBottom: 16, fontFamily: "DMSans", fontSize: 13, color: colors.textMuted }, actions: { flexDirection: "row", gap: 8 }, add: { flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.sunsetCoral }, addText: { fontFamily: "DMSans", fontSize: 13, fontWeight: "600", color: colors.white }, iconButton: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: 10 }, remove: { borderColor: colors.coralLight }, empty: { marginTop: 60, fontFamily: "DMSans", textAlign: "center", color: colors.textMuted } });
