import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Bell, Bus, Car, MapPin, Search, Smartphone, Vibrate, Volume2 } from "lucide-react-native";
import { api } from "../lib/api";
import { colors } from "../theme/colors";

export default function TransitAlarm() {
  const [routes, setRoutes] = useState([]); const [selectedRoute, setSelectedRoute] = useState(null); const [radius, setRadius] = useState(500); const [alarmOn, setAlarmOn] = useState(false); const [mode, setMode] = useState("vibrate"); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  const loadRoutes = async () => { setLoading(true); setError(null); try { const data = await api.getTransitRoutes(); const active = data.filter((route) => route.status === "ACTIVE"); setRoutes(active); setSelectedRoute((current) => current || active[0] || null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load transit routes."); } finally { setLoading(false); } };
  useEffect(() => { loadRoutes(); }, []);
  const modes = [["vibrate", "Vibrate", Vibrate], ["sound", "Sound", Volume2], ["push", "Push", Smartphone]];
  return <ScrollView contentContainerStyle={styles.screen}><View style={styles.header}><View><Text style={styles.title}>Transit Alarm</Text><Text style={styles.sub}>Proximity alerts using live routes from the transit database.</Text></View><Pressable onPress={() => setAlarmOn(true)} disabled={!selectedRoute} style={styles.coral}><Bell size={16} color="#fff" /><Text style={styles.buttonText}>Set Alarm</Text></Pressable></View><View style={styles.columns}><View style={styles.main}><View style={styles.card}><Text style={styles.heading}>Available Routes</Text><Pressable onPress={loadRoutes} style={styles.blue}><Search size={15} color="#fff" /><Text style={styles.buttonText}>Refresh routes</Text></Pressable></View>{loading ? <ActivityIndicator color={colors.oceanBlue} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{routes.map((route) => { const Icon = route.type === "BUS" ? Bus : Car; const selected = selectedRoute?.id === route.id; return <View key={route.id} style={[styles.card, selected && styles.selected]}><View style={styles.route}><Icon size={20} color={colors.oceanBlue} /><View style={{ flex: 1 }}><Text style={styles.name}>{route.name}</Text><Text style={styles.sub}>{route.type} · {route.stops} stops · {route.frequency}</Text></View></View><Pressable onPress={() => setSelectedRoute(route)} style={[styles.blue, selected && styles.coral]}><MapPin size={14} color="#fff" /><Text style={styles.buttonText}>{selected ? "Selected for alert" : "Select route"}</Text></Pressable></View>; })}</View><View style={styles.card}><Text style={styles.heading}>Stop Alarm</Text><Text style={styles.sub}>{selectedRoute ? `${selectedRoute.name} · ${selectedRoute.stops} stops` : "Select a route to configure an alert."}</Text><Text style={styles.sub}>Alert radius: {radius} m</Text><View style={styles.row}>{[100, 500, 1000, 2000].map((value) => <Pressable key={value} onPress={() => setRadius(value)} style={[styles.chip, radius === value && styles.chipActive]}><Text>{value} m</Text></Pressable>)}</View><View style={styles.row}>{modes.map(([key, label, Icon]) => <Pressable key={key} onPress={() => setMode(key)} style={[styles.mode, mode === key && styles.chipActive]}><Icon size={15} color={colors.oceanBlue} /><Text>{label}</Text></Pressable>)}</View><Pressable onPress={() => setAlarmOn((value) => !value)} disabled={!selectedRoute} style={[styles.enable, alarmOn && styles.coral]}><Text style={styles.buttonText}>{alarmOn ? "Alarm On" : "Enable Alarm"}</Text></Pressable></View></View></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flexGrow: 1, backgroundColor: "#F7F9FB", padding: 28 }, header: { flexDirection: "row", justifyContent: "space-between", gap: 16, marginBottom: 24 }, title: { fontFamily: "Poppins", fontSize: 26, fontWeight: "700", color: "#1A2E40" }, sub: { fontFamily: "DMSans", fontSize: 13, color: "#6B8CA8", marginTop: 4 }, columns: { flexDirection: "row", gap: 20, alignItems: "flex-start" }, main: { flex: 1, gap: 14 }, card: { backgroundColor: "#fff", borderRadius: 16, padding: 20, gap: 14, elevation: 2 }, selected: { borderWidth: 2, borderColor: colors.oceanBlue }, heading: { fontFamily: "Poppins", fontSize: 17, fontWeight: "700", color: "#1A2E40" }, coral: { flexDirection: "row", gap: 6, alignItems: "center", backgroundColor: colors.sunsetCoral, padding: 10, borderRadius: 10 }, blue: { flexDirection: "row", gap: 6, alignItems: "center", alignSelf: "flex-start", backgroundColor: colors.oceanBlue, padding: 10, borderRadius: 10 }, buttonText: { color: "#fff", fontFamily: "DMSans", fontWeight: "600" }, route: { flexDirection: "row", alignItems: "center", gap: 12 }, name: { fontFamily: "DMSans", fontWeight: "700", color: "#1A2E40" }, error: { color: colors.sunsetCoral }, row: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, chip: { padding: 7, borderRadius: 9, borderWidth: 1, borderColor: "#E2EBF3" }, chipActive: { borderColor: colors.sunsetCoral, backgroundColor: "#FFF1EE" }, mode: { alignItems: "center", gap: 4, padding: 8, borderRadius: 9, borderWidth: 1, borderColor: "#E2EBF3" }, enable: { alignItems: "center", backgroundColor: "#CBD5E0", padding: 11, borderRadius: 10 } });
